import flask
import psycopg2
import random

app = flask.Flask(__name__)

#
@app.route('/')
def welcome():
    return render_template("welcome.html")
    
@app.route('/random')
def state_pop():
    conn = psycopg2.connect(
        host="localhost",
        port=5432,
        database="richardsonc",
        user="richardsonc",
        password="berry437lamp")
  
    cur = conn.cursor()

    names = ["Aaron",
      "Abel",
      "Abraham",
      "Achilles",
      "Adam",
      "Adran",
      "Ammar",
      "Amon",
      "Arthur",
      "Artminas",
      "Boyd",
      "Brad",
      "Brandon",
      "Chuck",
      "Cicero",
      "Cinnabar",
      "Claudius",
      "Clay",
      "Clement",
      "Clive",
      "Cody",
      "Cole",
      "Colt",
      "Connor",
      "Conrad",
      "Cornelius",
      "Cozen",
      "Creon",
      "Crona",
      "Crow",
      "Cygnet",
      "Cypress",
      "Cyrus",
      "Daedalus",
      "Dalinar",
      "Damien",
      "Devin",
      "Dex",
      "Diar",
      "Diego",
      "Dimitri",
      "Dinell",
      "Diomedes",
      "Dior",
      "Dominic",
      "Donovan",
      "Dove",
      "Dragon",
      "Esker",
      "Ethan",
      "Eula",
      "Evaine",
      "Ezekiel",
      "Fabian",
      "Fahim",
      "Falco",
      "Falcon",
      "Faris",
      "Faust",
      "Feldspar",
      "Felix",
      "Ferdinand",
      "Ferguson",
      "Fern",
      "Feste",
      "Fraser",
      "Frederick",
      "Fritz",
      "Gabbro",
      "Gabriel",
      "Gael",
      "Gaius",
      "Galahad",
      "Izzy",
      "Jack",
      "Jackdaw",
      "Jackie",
      "Jacob",
      "Jaleel",
      "Jalen",
      "Jamal",
      "James",
      "Jamie",
      "Jason",
      "Jasper",
      "Jay",
      "Leon",
      "Leonardo",
      "Levi",
      "Lewis",
      "Liam",
      "Link",
      "Lloyd",
      "Loam",
      "Logan",
      "Lotus",
      "Louie",
      "Lucas",
      "Lucius",
      "Paul",
      "Pax",
      "Payton",
      "Pebble",
      "Penn",
      "Percy",
      "Peter",
      "Philip",
      "Phoenix",
      "Phos",
      "Pigeon",
      "Python",
      "Quail",
      "Quake",
      "Quan",
      "Quantum",
      "Quartz",
      "Quentin",
      "Quince",
      "Quincy",
      "Quirrel",
      "Radovan",
      "Raheem",
      "Raigh",
      "Rain",
      "Raj",
      "Rajul",
      "Rama",
      "Sigurd",
      "Valentine",
      "Valerian",
      "Vergil",
      "Victor",
      "Vin",
      "Vincent",
      "Wormwood",
      "Wren",
      "Xavier",
      "Xavos",
      "Xiao",
      "Yakub",
      "Zora",
      "Zote"]
    adjs = ["Great",
            "Gallant",
            "Destroyer",
            "Huge",
            "Majestic",
            "Terrible",
            "Scholar of the Burning Blood",
            "Scaleless",
            "Lord of Cinder",
            "Perfect",
           "Imperfect",
            "King",
            "Cursed",
            "Blessed"
           ]
    sql = "SELECT * FROM uscitypop;"
    randomyear = random.randint(1900, 2023)
    randomname = names[random.randint(0, len(names) - 1)]
    randomadj = adjs[random.randint(0, len(adjs) - 1)]
  
    cur.execute( sql  )

    row_list = cur.fetchall()
    randomplace = row_list[random.randint[0, len(row_list) - 1][0]
    
    return randomname + " the " + randomadj + " was born in " + randomplace + " in " + randomyear 
        
if __name__ == '__main__':
    my_port = 5124
    app.run(host='0.0.0.0', port = my_port) 
